audio:
  sample_rate: 16000

fillers:
  - euh
  - bah
  - genre
  - du coup
  - ben
  - en fait
  - voilà

postgres:
  host: localhost
  port: 5432
  user: interviewuser
  password: interviewpass
  dbname: pro8605
